#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -Wextra -Wall
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s -lSDL
OBJDIR_RELEASE = obj
DEP_RELEASE = 
OUT_RELEASE = bin/s25edit

OBJ_RELEASE = $(OBJDIR_RELEASE)/SGE/sge_shape.o $(OBJDIR_RELEASE)/SGE/sge_blib.o $(OBJDIR_RELEASE)/SGE/sge_bm_text.o $(OBJDIR_RELEASE)/SGE/sge_collision.o $(OBJDIR_RELEASE)/SGE/sge_misc.o $(OBJDIR_RELEASE)/SGE/sge_primitives.o $(OBJDIR_RELEASE)/SGE/sge_rotation.o $(OBJDIR_RELEASE)/SGE/sge_surface.o $(OBJDIR_RELEASE)/SGE/sge_textpp.o $(OBJDIR_RELEASE)/SGE/sge_tt_text.o $(OBJDIR_RELEASE)/callbacks.o $(OBJDIR_RELEASE)/globals.o $(OBJDIR_RELEASE)/CIO/CMenu.o $(OBJDIR_RELEASE)/CGame.o $(OBJDIR_RELEASE)/CGame_Cleanup.o $(OBJDIR_RELEASE)/CGame_Event.o $(OBJDIR_RELEASE)/CGame_GameLoop.o $(OBJDIR_RELEASE)/CGame_Init.o $(OBJDIR_RELEASE)/CGame_Render.o $(OBJDIR_RELEASE)/CIO/CButton.o $(OBJDIR_RELEASE)/CIO/CFile.o $(OBJDIR_RELEASE)/CIO/CFont.o $(OBJDIR_RELEASE)/CDebug.o $(OBJDIR_RELEASE)/CIO/CPicture.o $(OBJDIR_RELEASE)/CIO/CSelectBox.o $(OBJDIR_RELEASE)/CIO/CTextfield.o $(OBJDIR_RELEASE)/CIO/CWindow.o $(OBJDIR_RELEASE)/CMap.o $(OBJDIR_RELEASE)/CSurface.o

all: release

clean: clean_release

before_release: 
	test -d bin || mkdir -p bin
	test -d $(OBJDIR_RELEASE)/SGE || mkdir -p $(OBJDIR_RELEASE)/SGE
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/CIO || mkdir -p $(OBJDIR_RELEASE)/CIO

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/SGE/sge_shape.o: SGE/sge_shape.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SGE/sge_shape.cpp -o $(OBJDIR_RELEASE)/SGE/sge_shape.o

$(OBJDIR_RELEASE)/SGE/sge_blib.o: SGE/sge_blib.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SGE/sge_blib.cpp -o $(OBJDIR_RELEASE)/SGE/sge_blib.o

$(OBJDIR_RELEASE)/SGE/sge_bm_text.o: SGE/sge_bm_text.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SGE/sge_bm_text.cpp -o $(OBJDIR_RELEASE)/SGE/sge_bm_text.o

$(OBJDIR_RELEASE)/SGE/sge_collision.o: SGE/sge_collision.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SGE/sge_collision.cpp -o $(OBJDIR_RELEASE)/SGE/sge_collision.o

$(OBJDIR_RELEASE)/SGE/sge_misc.o: SGE/sge_misc.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SGE/sge_misc.cpp -o $(OBJDIR_RELEASE)/SGE/sge_misc.o

$(OBJDIR_RELEASE)/SGE/sge_primitives.o: SGE/sge_primitives.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SGE/sge_primitives.cpp -o $(OBJDIR_RELEASE)/SGE/sge_primitives.o

$(OBJDIR_RELEASE)/SGE/sge_rotation.o: SGE/sge_rotation.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SGE/sge_rotation.cpp -o $(OBJDIR_RELEASE)/SGE/sge_rotation.o

$(OBJDIR_RELEASE)/SGE/sge_surface.o: SGE/sge_surface.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SGE/sge_surface.cpp -o $(OBJDIR_RELEASE)/SGE/sge_surface.o

$(OBJDIR_RELEASE)/SGE/sge_textpp.o: SGE/sge_textpp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SGE/sge_textpp.cpp -o $(OBJDIR_RELEASE)/SGE/sge_textpp.o

$(OBJDIR_RELEASE)/SGE/sge_tt_text.o: SGE/sge_tt_text.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SGE/sge_tt_text.cpp -o $(OBJDIR_RELEASE)/SGE/sge_tt_text.o

$(OBJDIR_RELEASE)/callbacks.o: callbacks.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c callbacks.cpp -o $(OBJDIR_RELEASE)/callbacks.o

$(OBJDIR_RELEASE)/globals.o: globals.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c globals.cpp -o $(OBJDIR_RELEASE)/globals.o

$(OBJDIR_RELEASE)/CIO/CMenu.o: CIO/CMenu.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CIO/CMenu.cpp -o $(OBJDIR_RELEASE)/CIO/CMenu.o

$(OBJDIR_RELEASE)/CGame.o: CGame.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CGame.cpp -o $(OBJDIR_RELEASE)/CGame.o

$(OBJDIR_RELEASE)/CGame_Cleanup.o: CGame_Cleanup.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CGame_Cleanup.cpp -o $(OBJDIR_RELEASE)/CGame_Cleanup.o

$(OBJDIR_RELEASE)/CGame_Event.o: CGame_Event.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CGame_Event.cpp -o $(OBJDIR_RELEASE)/CGame_Event.o

$(OBJDIR_RELEASE)/CGame_GameLoop.o: CGame_GameLoop.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CGame_GameLoop.cpp -o $(OBJDIR_RELEASE)/CGame_GameLoop.o

$(OBJDIR_RELEASE)/CGame_Init.o: CGame_Init.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CGame_Init.cpp -o $(OBJDIR_RELEASE)/CGame_Init.o

$(OBJDIR_RELEASE)/CGame_Render.o: CGame_Render.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CGame_Render.cpp -o $(OBJDIR_RELEASE)/CGame_Render.o

$(OBJDIR_RELEASE)/CIO/CButton.o: CIO/CButton.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CIO/CButton.cpp -o $(OBJDIR_RELEASE)/CIO/CButton.o

$(OBJDIR_RELEASE)/CIO/CFile.o: CIO/CFile.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CIO/CFile.cpp -o $(OBJDIR_RELEASE)/CIO/CFile.o

$(OBJDIR_RELEASE)/CIO/CFont.o: CIO/CFont.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CIO/CFont.cpp -o $(OBJDIR_RELEASE)/CIO/CFont.o

$(OBJDIR_RELEASE)/CDebug.o: CDebug.cpp
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CDebug.cpp -o $(OBJDIR_RELEASE)/CDebug.o

$(OBJDIR_RELEASE)/CIO/CPicture.o: CIO/CPicture.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CIO/CPicture.cpp -o $(OBJDIR_RELEASE)/CIO/CPicture.o

$(OBJDIR_RELEASE)/CIO/CSelectBox.o: CIO/CSelectBox.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CIO/CSelectBox.cpp -o $(OBJDIR_RELEASE)/CIO/CSelectBox.o

$(OBJDIR_RELEASE)/CIO/CTextfield.o: CIO/CTextfield.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CIO/CTextfield.cpp -o $(OBJDIR_RELEASE)/CIO/CTextfield.o

$(OBJDIR_RELEASE)/CIO/CWindow.o: CIO/CWindow.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CIO/CWindow.cpp -o $(OBJDIR_RELEASE)/CIO/CWindow.o

$(OBJDIR_RELEASE)/CMap.o: CMap.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CMap.cpp -o $(OBJDIR_RELEASE)/CMap.o

$(OBJDIR_RELEASE)/CSurface.o: CSurface.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CSurface.cpp -o $(OBJDIR_RELEASE)/CSurface.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin
	rm -rf $(OBJDIR_RELEASE)/SGE
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/CIO

.PHONY: before_release after_release clean_release

